// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://igyfsivungjotgdzqrnf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlneWZzaXZ1bmdqb3RnZHpxcm5mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1MTI2MDIsImV4cCI6MjA2OTA4ODYwMn0.rTZzhLbvGsd7nH-WZoxGlvBDQY6U1yhsD5DdyhyQxmA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});